{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "counternew.serviceAccountName" . }}
  labels:
{{ include "counternew.labels" . | indent 4 }}
{{- end -}}
